scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'grafana'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3000']
  - job_name: 'gateway-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['localhost:9092']
  - job_name: 'elastic-query-service-1'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['localhost:9193']
  - job_name: 'elastic-query-service-2'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'localhost:9195' ]
  - job_name: 'kafka-streams-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['localhost:9197']
